name:                binks
version:             0.0.1
github:              "breakerzirconia/binks"
license:             MIT
author:              "Constantine Ter-Matevosian"
maintainer:          "terkot1010@gmail.com"
copyright:           "2022 Constantine Ter-Matevosian"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/binks#readme>

default-extensions:
- LambdaCase
- OverloadedStrings
- RecordWildCards
- TypeApplications

dependencies:
- base >= 4.7 && < 5
- containers
- haskeline
- megaparsec
- mtl
- text
- transformers
- scientific

library:
  source-dirs: src

executables:
  binks:
    main:                Main.hs
    source-dirs:         app/interpreter
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binks

  binksi:
    main:                Main.hs
    source-dirs:         app/repl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binks

tests:
  binks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binks
